module.exports = function(){

    var data = {
        Exercices :[
             {id:1,tp:1,name:"Exercice 1 tp1",descreption:"create a function that calculate the age of a giving birtdate : ",template:`<form class="form-group"><label for="date">Birth Date :</label><input name="date" class="form-control" id="temp" type="text"><label for="age">Your age :</label><p id='result'></p></form>`,  solution:`var aujourdhui = new Date(); var tableau = val_date.split("-");var an   = tableau[0];var mo = tableau[1];var jour = tableau[2];var age = aujourdhui.getFullYear()- an;var mois = (aujourdhui.getMonth()+1)+ - mo;if (mois < 0  || (mois === 0 && aujourdhui.getDate() < jour ))age = age - 1;document.getElementById('result').textContent =age;`},
             {id:2,tp:1,name:"Exercice 2 tp1",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class="btn btn-primary"  (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:3,tp:2,name:"Exercice 1 tp2",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class="btn btn-primary" (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:4,tp:2,name:"Exercice 2 tp2",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class="btn btn-primary"  (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:5,tp:3,name:"Exercice 1 tp3",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class='btn btn-primary' (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:6,tp:3,name:"Exercice 2 tp3",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class='btn btn-primary'  (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:7,tp:4,name:"Exercice 1 tp4",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class='btn btn-primary' (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"},
             {id:8,tp:4,name:"Exercice 2 tp4",descreption:"create a function that gets a number and returns its multication table tell number 12 ",template:`<button class='btn btn-primary'  (click)="showConsoledata()">show console data</button>`,  solution:"function produit_alert(nb){function is_int(value){if((parseFloat(value) == parseInt(value)) && !isNaN(value)){return true;}else{return false;} } while(is_int(nb)==false){ var nb = prompt('entrer un nombre'); } var tab = new Array(12);for (var i=1;i<=12; i++){tab[i] = nb*i; } var html=new String(); html=html.concat('<center><h4> La table de multiplication de '+nb+'</h4> </center>'); html=html.concat('<center> <table class='table table-bordered' id='tab'> </center>');for (var i in tab){ html=html.concat('<tr style='height:2px;'><td><center>'+nb+ '</center></td> <td><center> * </center></td> <td><center> '  +i+ ' </center></td> <td><center>=</center></td>  <td><center>'+tab[i]+'</center></td></tr>');} document.getElementById('result1').innerHTML=html; }"}
         ],
         Tps :[
             {id: 1, name:"tp1"},
             {id: 2, name:"tp2"},
             {id: 3, name:"tp3"},
             {id: 4, name:"tp4"},
         ],
         Admins:[
             {id:1,name : "mohamed", password:"med@123fata"}
         ]
    }
    return data;
}